### ISSUE TITLE
recursive_delete deprecated

### ISSUE THREAD

**Issue by rahearn** [18F/terraform-cloudgov#35]
Remove `recursive_delete` argument as it is deprecated.

Potentially replace with some other control that prevents deletion of production resources

**Comment by rahearn** [comment]
Potentially https://developer.hashicorp.com/terraform/tutorials/state/resource-lifecycle#prevent-resource-deletion

**Comment by jskinne3** [comment]
Sadly, the `lifecycle` block does not support variables, [only literal values](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#literal-values-only). So it will not be configurable with an argument. Thus it can't be a direct substitute for `recursive_delete`.

**Comment by rahearn** [comment]
> Sadly, the `lifecycle` block does not support variables, [only literal values](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#literal-values-only). So it will not be configurable with an argument. Thus it can't be a direct substitute for `recursive_delete`.

Ah, bummer, but thank you for doing that research and sharing
